name: Tests

on: ['push', 'pull_request']

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        php: ['7.4']
        dependency-version: [prefer-lowest, prefer-stable]

    name: PHP ${{ matrix.php }} - ${{ matrix.os }} - ${{ matrix.dependency-version }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        tools: composer
        coverage: none

    - name: Setup Problem Matches
      run: |
        echo "::add-matcher::${{ runner.tool_cache }}/php.json"
        echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

    - name: Install IPFS
      run: |
        mkdir .temp && cd .temp
        wget https://dist.ipfs.io/go-ipfs/v0.10.0/go-ipfs_v0.10.0_linux-amd64.tar.gz
        tar -xvzf go-ipfs_v0.10.0_linux-amd64.tar.gz
        cd go-ipfs
        sudo bash install.sh
        ipfs init --profile server
        ipfs daemon &
        echo "127.0.0.1 ipfs" | sudo tee -a /etc/hosts

    - name: Install PHP dependencies
      run: composer update --${{ matrix.dependency-version }} --no-interaction --no-progress --ansi

    - name: Unit Tests
      run: vendor/bin/phpunit --colors=always
